### PR TITLE
Fix patching 1-clik links loaded after page ready

### LINKED ISSUE #176: 1-click nzb downloading not working with nzbindex.com
1-click nzb downloading not working with nzbindex.com not working with Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by gissehel**
Should fix #176 .

### CODE REVIEW

File: scripts/content/nzbindex.js [hunk 1]
```diff
@@ -1,84 +1,102 @@
...
-	
-	$('table a[href*="nzbindex.nl\\/download\\/"]').each(function() {
-	    var img = chrome.extension.getURL('/images/sab2_16.png');
-	    var href = $(this).attr('href');
-	    var link = '<a class="addSABnzbdOnClick" href="' + href + '"><img title="Send to SABnzbd" src="' + img + '" /></a> ';
-	    $(this).before(link);
-	});
+    $('input[value="Create NZB"]').each(function () {
+        if ($(this).attr('x-nzbpatched') !== 'true') {
+            $(this).attr('x-nzbpatched', 'true');
```
Comment (gboudreau) [inline scripts/content/nzbindex.js:51]: Missing `x-nzbpatched="true"` on line 54?

Comment (gissehel) [reply scripts/content/nzbindex.js:51]: Sorry, I missed the notification for the comment.

The `x-nzbpatched` attribute was added because the old code was only working if that portion of code was run once. Because nzbindex now used async loading of result, it should be run each time the DOM is changed. It should not add a new link each time.

The lines like 50 and 51 should have been enough for that but... The pattern to find the "nzb download link" also trigger the new "add nzb link". Thus I've also added the `x-nzbpatched` attribute to the new created link.

The new input doesn't trigger the query used for addition, thus I didn't added it.

After second reflexion, it doesn't break anything, and in case of code evolution where the new added "input" would trigger the query, I've also added it in a new commit.

Also, there was a bug were the line 81 was adding several time the same trigger (instead of replacing it) at each run of the function, thus I've moved the code in the creation of the link.
